
forEach: BoundedContext
fileName: application.yml
path: {{name}}/src/main/resources
---
server:
  port: 8080
  error:
    include-message: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://${DOCKER_HOST_IP:localhost}/{{name}}_db?createDatabaseIfNotExist=true
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  profiles: default
//<<< Etc / RSocket
  rsocket:
    server:
      mapping-path: /rsocket
      transport: websocket
      port: {{contexts.rSocketPort}}
//>>> Etc / RSocket

server:
  port: {{portGenerated}}

---
spring:
  profiles: docker

  rsocket:
    server:
      mapping-path: /rsocket
      transport: websocket
      port: 7000

<function>

this.contexts.rSocketPort = parseInt(this.portGenerated) - 1080    // make port number from 7001

</function>